[package]
name = "ts-gettext-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
indexmap = "2.2.6"
walkdir = "2"

[[bin]]
name = "ts-gettext-extractor"
path = "main.rs"

[dev-dependencies]
pretty_assertions = "1.4.0"
