on:
  pull_request:
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

name: Lint

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
